# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pepimessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pepimessage.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11pepimessage.proto\"\xd9\x04\n\x07\x43ommand\x12\x1d\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x0c.Command.Cmd\x12\x0e\n\x06values\x18\x02 \x03(\x05\"\x9e\x04\n\x03\x43md\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0b\n\x07SET_ISO\x10\x01\x12\x0b\n\x07GET_ISO\x10\x65\x12\x15\n\x11SET_SHUTTER_SPEED\x10\x02\x12\x15\n\x11GET_SHUTTER_SPEED\x10\x66\x12\x12\n\x0eGET_BRIGHTNESS\x10\x03\x12\x12\n\x0eSET_BRIGHTNESS\x10g\x12\x11\n\rSET_AWB_GAINS\x10\x04\x12\x11\n\rGET_AWB_GAINS\x10h\x12\x12\n\x0eSET_RESOLUTION\x10\x05\x12\x12\n\x0eGET_RESOLUTION\x10i\x12\x11\n\rSET_SHARPNESS\x10\x06\x12\x11\n\rGET_SHARPNESS\x10j\x12\x12\n\x0eSET_SATURATION\x10\x07\x12\x12\n\x0eGET_SATURATION\x10k\x12\x0c\n\x08SET_ZOOM\x10\x08\x12\x0c\n\x08GET_ZOOM\x10l\x12\x12\n\rSET_SERVER_ID\x10\xc8\x01\x12\x12\n\rGET_SERVER_ID\x10\xc9\x01\x12\x17\n\x12\x45NABLE_COMPRESSION\x10\xca\x01\x12\x18\n\x13\x44ISABLE_COMPRESSION\x10\xcb\x01\x12\x0e\n\tGET_STILL\x10\xac\x02\x12\x12\n\rSTILL_SUCCESS\x10\xb3\x02\x12\x12\n\rSTILL_FAILURE\x10\xb4\x02\x12\x11\n\x0cSTART_STREAM\x10\x90\x03\x12\x10\n\x0bSTOP_STREAM\x10\x91\x03\x12\x14\n\x0f\x43OMMAND_SUCCESS\x10\xbc\x05\x12\x14\n\x0f\x43OMMAND_FAILURE\x10\xa0\x06\"0\n\x05Image\x12\x14\n\x0cimg_data_str\x18\x01 \x01(\x0c\x12\x11\n\tserver_id\x18\x02 \x01(\t\"J\n\x0bPepiMessage\x12\x1b\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x08.CommandH\x00\x12\x17\n\x05image\x18\x02 \x01(\x0b\x32\x06.ImageH\x00\x42\x05\n\x03msgb\x06proto3')
)



_COMMAND_CMD = _descriptor.EnumDescriptor(
  name='Cmd',
  full_name='Command.Cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ISO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_ISO', index=2, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SHUTTER_SPEED', index=3, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_SHUTTER_SPEED', index=4, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_BRIGHTNESS', index=5, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_BRIGHTNESS', index=6, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_AWB_GAINS', index=7, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_AWB_GAINS', index=8, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_RESOLUTION', index=9, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_RESOLUTION', index=10, number=105,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SHARPNESS', index=11, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_SHARPNESS', index=12, number=106,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SATURATION', index=13, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_SATURATION', index=14, number=107,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ZOOM', index=15, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_ZOOM', index=16, number=108,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_SERVER_ID', index=17, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_SERVER_ID', index=18, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENABLE_COMPRESSION', index=19, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISABLE_COMPRESSION', index=20, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_STILL', index=21, number=300,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STILL_SUCCESS', index=22, number=307,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STILL_FAILURE', index=23, number=308,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_STREAM', index=24, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_STREAM', index=25, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_SUCCESS', index=26, number=700,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_FAILURE', index=27, number=800,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=81,
  serialized_end=623,
)
_sym_db.RegisterEnumDescriptor(_COMMAND_CMD)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='Command.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='Command.values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMAND_CMD,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=623,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img_data_str', full_name='Image.img_data_str', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='Image.server_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=673,
)


_PEPIMESSAGE = _descriptor.Descriptor(
  name='PepiMessage',
  full_name='PepiMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='PepiMessage.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='PepiMessage.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='PepiMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=675,
  serialized_end=749,
)

_COMMAND.fields_by_name['command'].enum_type = _COMMAND_CMD
_COMMAND_CMD.containing_type = _COMMAND
_PEPIMESSAGE.fields_by_name['command'].message_type = _COMMAND
_PEPIMESSAGE.fields_by_name['image'].message_type = _IMAGE
_PEPIMESSAGE.oneofs_by_name['msg'].fields.append(
  _PEPIMESSAGE.fields_by_name['command'])
_PEPIMESSAGE.fields_by_name['command'].containing_oneof = _PEPIMESSAGE.oneofs_by_name['msg']
_PEPIMESSAGE.oneofs_by_name['msg'].fields.append(
  _PEPIMESSAGE.fields_by_name['image'])
_PEPIMESSAGE.fields_by_name['image'].containing_oneof = _PEPIMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['PepiMessage'] = _PEPIMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'pepimessage_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'pepimessage_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)

PepiMessage = _reflection.GeneratedProtocolMessageType('PepiMessage', (_message.Message,), dict(
  DESCRIPTOR = _PEPIMESSAGE,
  __module__ = 'pepimessage_pb2'
  # @@protoc_insertion_point(class_scope:PepiMessage)
  ))
_sym_db.RegisterMessage(PepiMessage)


# @@protoc_insertion_point(module_scope)
